set(CMAKE_AR                    i686-elf-ar)
set(CMAKE_ASM_COMPILER          i686-elf-as)
set(CMAKE_C_COMPILER            i686-elf-gcc)
set(CMAKE_CXX_COMPILER          i686-elf-g++)
set(CMAKE_LINKER                i686-elf-ld)
set(CMAKE_OBJCOPY               i686-elf-objcopy)
set(CMAKE_RANLIB                i686-elf-ranlib)
set(CMAKE_SIZE                  i686-elf-size)
set(CMAKE_STRIP                 i686-elf-strip)

set(CMAKE_SYSTEM_NAME           elf)
set(CMAKE_SYSTEM_PROCESSOR      i686)

set(CMAKE_C_FLAGS               "-std=gnu99 -ffreestanding -O2 -Wall -Wextra -nostdlib -lgcc")
set(CMAKE_CXX_FLAGS             "-std=gnu99 -ffreestanding -O2 -Wall -Wextra -nostdlib -lgcc")
#set(CMAKE_C_FLAGS_DEBUG         <c_flags_for_debug>)
#set(CMAKE_C_FLAGS_RELEASE       <c_flags_for_release>)
#set(CMAKE_CXX_FLAGS_DEBUG       <cpp_flags_for_debug>)
#set(CMAKE_CXX_FLAGS_RELEASE     <cpp_flags_for_release>)
set(CMAKE_EXE_LINKER_FLAGS      "-std=gnu99 -ffreestanding -O2 -Wall -Wextra -nostdlib -lgcc -T ${CMAKE_SOURCE_DIR}/linker.ld")